# Generated by Django 4.0.7 on 2024-02-16 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notas',
            old_name='data_criado',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='notas',
            old_name='data_atualizado',
            new_name='date_updated',
        ),
        migrations.RenameField(
            model_name='notas',
            old_name='titulo',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='notas',
            old_name='id_usuario',
            new_name='user',
        ),
    ]
